USE BARCODE_LETICIA;
GO 

CREATE TABLE Boxes (
id INT IDENTITY PRIMARY KEY,
UsuarioId INT NOT NULL,
Status VARCHAR(20) NOT NULL DEFAULT 'ABERTA',
DataCriacao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

CONSTRAINT FK_Boxes_Users
FOREIGN KEY (UsuarioId) REFERENCES dbo.Users(Id)
);
