USE BARCODE_LETICIA
GO 

CREATE TABLE BoxProdutos (
Id INT IDENTITY PRIMARY KEY,
BoxId INT NOT NULL,
ProdutoId INT NOT NULL,
DataLeitura DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

CONSTRAINT FK_BoxProdutos_Box
FOREIGN KEY (BoxId) REFERENCES Boxes(Id),

CONSTRAINT FK_BoxProdutos_Produto
FOREIGN KEY (ProdutoId)  REFERENCES Produtos(Id),

CONSTRAINT UQ_BoxProduto UNIQUE (BoxId, ProdutoId)
);
